import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [Email, setEmail] = useState('');

  return (
    <div className={styles.container}>
      <Head>
        <title>Summit Qr Scanner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>QR Scanning</h1>
        <hr height="1px" width="40%"/>
        <label>
          Input Email: <input value={Email} onChange={(e) => setEmail(e.target.value)} />
        </label> 
        <button type="submit" className={styles.qrButton} onClick={() => console.log({ Email })}>
          Get my QR Code!
        </button>

        <div className={styles.grid}>
          <Link href="/scan" className={styles.card}>
            <a>
              <h2>Scan QR Code &rarr;</h2>
            </a>
          </Link>
          {" "}
          <Link href="/airtable" className={styles.card}>
            <a>
              <h2> Generate a qr code&rarr;</h2>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );

  function handleSubmit(e) {
    const formJson = Object.fromEntries(formData.entries());
    console.log(formJson);
  }
}
